version: '3.8'

services:
  url-shortener:
    build:
      context: .
      dockerfile: dockerfile
    container_name: url-shortener-api
    ports:
      - "5000:5000" # Map local port 8080 to container port 8080
    volumes:
      - .:/app # Mount the current directory to /app in the container
    restart: always
    environment:
      - GIN_MODE=release # Set Gin framework mode to production
