version: "3.8"

services:
  url-shortener-api:
    build: .
    ports:
      - "5000:5000"  # Mapping container port 5000 to host port 5000
    networks:
      - my_network  # Optional: Only if you want to configure networks for your services

networks:
  my_network:  # Optional: Define custom network if required
    driver: bridge
